DataBiosphere/terra-interoperability-model

src/terra-core/TerraCoreDataModel.ttl

Fix equivalentClass usage

---

src/references/EFO_subset.xml.rdf
src/terra-core/TerraCoreDataModel.ttl

[DSPDC-1048](https://broadinstitute.atlassian.net/browse/DSPDC-1048)

Added LibraryPrepType and single cell activities

---

src/terra-core/TerraCoreDataModel.ttl

[Jira Ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1076)
These changes add:
- a MouseDonor object
- a hasStrain property
- a hasDevelopmentalStage property
There are also some changes that come from loading the file into my version of TopBraid Composer.

Get imports working in TopBraid, add MouseDonor, hasStrain, and hasDevelopmentalStage

---

src/references/EFO_subset.xml.rdf
src/references/NCBITaxon/NCBITaxon_Organisms.owl.xml.rdf
src/references/OBI/OBI_assaySubset.xml.rdf
src/references/OBI/OBI_core.xml.rdf
src/terra-core/TerraCoreDataModel.ttl

Specifics about the implications of the changes are [DSPDC-1039](https://broadinstitute.atlassian.net/browse/DSPDC-1039) 
Also includes [DSPDC-1023](https://broadinstitute.atlassian.net/browse/DSPDC-1023)

Add SingleCell support for SCP; cleaned up references

---

src/references/OBI/OBI_core.xml.rdf
src/terra-core/TerraCoreDataModel.ttl

Added family history and diagnosis.  See https://broadinstitute.atlassian.net/browse/DSPDC-1158, https://broadinstitute.atlassian.net/browse/DSPDC-1117.

Add Diagnosis and Family History

---

src/references/terra-dcat-ap/TerraDCAT-AP.ttl
src/terra-core/TerraCoreDataModel.ttl

Updating the data model to switch xsd:anyURI to dct:URI (3 instances)

QH-DSPDC-1147-uri-definition

---

README.md
documents/Ontologies.md

Added reference in README and created separate file for table of ontologies and vocabularies in use.

Publish ontologies in use

---

docs/index.html

Updated html

---

src/terra-core/TerraCoreDataModel.ttl

Add fields to support cancer data.

---

README.md
webpages/TerraCoreDataModel.html
webpages/references/CL_subset.html
webpages/references/EFO_subset.html
webpages/references/NCBITaxon_Organisms.html
webpages/references/OBI_assay_subset.html
webpages/references/OBI_core.html
webpages/references/UBERON_subset.html

[DSPDC-1345](https://broadinstitute.atlassian.net/browse/DSPDC-1345)

Updated text format for references; updated release info.

---

src/terra-core/TerraCoreDataModel.ttl
src/terra-core/TerraDCAT-AP.ttl

As it says [Best Practices](https://broadinstitute.atlassian.net/wiki/spaces/DSPCDM/pages/854360084/Terra+Interoperability+Model+Best+Practices) 
More info: [DSPDC-1389](https://broadinstitute.atlassian.net/browse/DSPDC-1389)

Aligning with Best Practices naming conventions.

---

src/terra-core/TerraCoreDataModel.ttl
src/terra-core/TerraDCAT-AP.ttl

[DSPDC-1644](https://broadinstitute.atlassian.net/browse/DSPDC-1644) 
Also a few cleanup items.

Update DUO terms, restrictions, uses

---

src/extensions/epigenomics/Encode.ttl
src/extensions/epigenomics/EncodeExamples.ttl

Model and examples were updated to be consistent with current core 
[See DSPDC-1274](model.https://broadinstitute.atlassian.net/browse/DSPDC-1274)

Update Encode model and examples

---

tools/data-model-exporter/data_model_exporter/dmExporter.py

Want to clarify command line when running dmExporter tool
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1650)
- update command for no arguments to give sample arguments
- confirmation for overwriting existing json file

Ep dspdc 1650

---

.github/workflows/major-release.yaml
.github/workflows/minor-release.yaml
.gitignore

We want to build a release workflow for TIM, for minor and major versions.
Implements the major version release process.

[DSPDC-1606] Add workflow for major release

---

src/terra-core/TerraCoreValueSets.ttl
src/terra-core/TerraDCAT-AP.ttl

[DSPDC-1675](https://broadinstitute.atlassian.net/browse/DSPDC-1675)

Minor modifications to data modality, add definitions

---

src/terra-core/TerraCoreDataModel.ttl
src/terra-core/TerraDCAT-AP.ttl

Fix cardinality restrictions.
[DM-358](https://broadworkbench.atlassian.net/browse/DM-358)
As a result of CMAP cleanup,  HCA review, additional Epigenomics modeling, some minor corrections to the data model.
[DM-358](https://broadworkbench.atlassian.net/browse/DM-358)

Update cardinality restrictions plus inconsistencies. 

---

src/terra-core/TerraDCAT-AP.ttl

[DM-408](https://broadworkbench.atlassian.net/browse/DM-408)
[DM-409](https://broadworkbench.atlassian.net/browse/DM-409)

Fix errors related to cardinality restrictions.

---

src/terra-core/TerraCoreDataModel.ttl

Reverts DataBiosphere/terra-interoperability-model#69

Revert "Column names"

---

src/terra-core/TerraCoreDataModel.ttl

See [DM-382](https://broadworkbench.atlassian.net/browse/DM-382)

Additions to align w ENCODE

---

src/terra-core/TerraCoreDataModel.ttl

Sid bugfix

---

src/terra-core/TerraCoreDataModel.ttl

[DM-421](https://broadworkbench.atlassian.net/browse/DM-421 )

Adding VariantCall and related entities/properties

---

releases/2.x/imports/OBIAssay_subset.xml.rdf
releases/2.x/terra-core/TerraCoreDataModel.ttl
releases/2.x/terra-core/TerraCoreValueSets.ttl
src/terra-core/TerraCoreDataModel.ttl
src/terra-core/TerraCoreValueSets.ttl
webpages/www/imports/OBIAssay_subset.html

Removed comments.  Added import subdirectory to import statements.  Also removed comments at start. [DM-463](https://broadworkbench.atlassian.net/browse/DM-463)

Updated imports & release/webpage

---

webpages/www/imports/dublin_core_terms.html

Missed this in my previous check in!

Need to include html file for proper referencing of URL.

---

webpages/Dockerfile

Update packages due to https://github.com/DataBiosphere/terra-interoperability-model/runs/8059950391?check_suite_focus=true

[DDO-2300] Fix datamodel image

---

webpages/httpd-container.conf

Add proxy rules for dublin_core_terms

[DDO-2301] Dublin Core Terms

---

src/terra-core/TerraDCAT-AP.ttl

hasCustodian is an annotation property; no restrictions are allowed.  
[DM-500](https://broadworkbench.atlassian.net/browse/DM-500)

Remove illegal restrictions on annotation properties.

---

src/terra-core/TerraCoreDataModel.ttl

[DM-505](https://broadworkbench.atlassian.net/browse/DM-505)

Removed restrictions and fixed other minor issues.
